# Site settings
title: marsicdev
email: marsicdev@gmail.com
description: "Blog about programming, travel and stuff"
baseurl: "http://marsicdev.github.io"
url: "http://marsicdev.github.io"
twitter_username: marsic
github_username:  marsicdev
# facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["node_modules"]
