# Site settings
title:       marsic|dev
email:       marsicdev@gmail.com
author:      Marko Arsić
description: "Programming is what I do."
baseurl:     ""
url:         "https://marsic.info"

# Google analytics
google_analytics: UA-30594419-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: marsicdev
stackoverflow_id:
twitter_username: marsic
google_plus_id:
linkedin_username: marsic
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
