# Site settings
title: marsicdev
email: marsicdev@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "http://marsicdev.github.io"
url: "http://marsicdev.github.io"
twitter_username: marsic
github_username:  marsicdev
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
