# Site settings
title: marsic|dev
email: marsicdev@gmail.com
author: Marko Arsić
description: "Programming is what I do."
baseurl: ""
url: "https://marsic.dev"

# Google analytics
google_analytics: UA-133876990-2

# Optional features
animated: false
show_related_posts: false
show_post_footers: false

# Social icons
show_social_icons: true
github_username: marsicdev
stackoverflow_id:
twitter_username: marsic
google_plus_id:
linkedin_username: marsic
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: "Share this post!"
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_linkedin: true
share_reddit: false
